site_name: PKM
docs_dir: /opt/cryptex/data/pkm
site_dir: /opt/cryptex/data/notes-output

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
